apiVersion: v1
kind: Service
metadata:
  name: tf-serving-geo-model
spec:
  type: ClusterIP # default service type is always ClusterIP (i.e., internal service)
  selector:
    app: tf-serving-geo-model
  ports:
  - port: 8500
    targetPort: 8500
